# Generated by Django 2.2 on 2019-04-06 13:54

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_nipype.models.fields
import django_nipype.models.interfaces.fsl.bet.bet_configuration
import django_nipype.models.interfaces.fsl.bet.choices.mode
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('fractional_intensity_threshold', models.FloatField(default=0.5, help_text='Fractional intensity threshold')),
                ('vertical_gradient', models.FloatField(default=0, help_text='Vertical gradient in fractional intensity threshold (-1, 1)')),
                ('head_radius', models.PositiveIntegerField(blank=True, help_text='Head radius in millimeters (mm)', null=True)),
                ('gravity_center', models.CharField(blank=True, help_text='Initial mesh surface center of gravity in voxels', max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('threshold_segmented', models.BooleanField(default=False, help_text='Apply thresholding to segmented brain image and mask')),
                ('mode', models.CharField(choices=[('NORMAL', 'Normal'), ('ROBUST', 'Robust'), ('PADDNG', 'Padding'), ('REMOVE', 'Remove Eyes'), ('SURFAC', 'Surfaces'), ('FUNCTN', 'Funational'), ('REDUBI', 'Reduce Bias')], default=django_nipype.models.interfaces.fsl.bet.choices.mode.Mode('Normal'), max_length=4)),
                ('base_output_name', models.CharField(blank=True, max_length=55, null=True)),
                ('output', django_nipype.models.fields.ChoiceArrayField(base_field=models.CharField(choices=[('BRN', 'Brain'), ('OUT', 'Surface Outline'), ('SRF', 'Surfaces'), ('MSK', 'Mask'), ('MSH', 'Mesh Surface')], max_length=3), blank=True, default=django_nipype.models.interfaces.fsl.bet.bet_configuration.default_output, size=5)),
            ],
            options={
                'verbose_name_plural': 'FSL BET Configurations',
            },
        ),
        migrations.CreateModel(
            name='BetRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('log', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django_nipype.BetConfiguration')),
            ],
            options={
                'verbose_name_plural': 'FSL BET Runs',
            },
        ),
        migrations.CreateModel(
            name='BetOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('path', models.FilePathField(unique=True)),
                ('output_type', models.CharField(choices=[('BRN', 'Brain'), ('OUT', 'Surface Outline'), ('SRF', 'Surfaces'), ('MSK', 'Mask'), ('MSH', 'Mesh Surface')], max_length=3)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_set', to='django_nipype.BetRun')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('path', models.FilePathField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_set', to='django_nipype.BetRun')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
