# Generated by Django 2.1.4 on 2019-01-21 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fractional_intensity_threshold', models.FloatField(default=0.5, help_text='Fractional intensity threshold')),
                ('vertical_gradient', models.FloatField(default=0, help_text='Vertical gradient in fractional intensity threshold (-1, 1)')),
                ('head_radius', models.PositiveIntegerField(blank=True, help_text='Head radius in millimeters (mm)', null=True)),
                ('gravity_center', models.CharField(blank=True, help_text='Initial mesh surface center of gravity in voxels', max_length=30, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('threshold_segmented', models.BooleanField(default=False, help_text='Apply thresholding to segmented brain image and mask')),
                ('output_surface_outline', models.BooleanField(default=False, help_text='Create surface outline image')),
                ('output_binary_mask', models.BooleanField(default=False, help_text='Create binary mask image')),
                ('output_skull', models.BooleanField(default=False, help_text='Create skull image')),
                ('no_output', models.BooleanField(default=False, help_text="Don't generate segmented output")),
                ('output_mesh_surface', models.BooleanField(default=False, help_text='Generate a VTK mesh brain surface')),
                ('robust', models.BooleanField(default=False, help_text='Robust brain center estimation (iterates BET several times)')),
                ('padding', models.BooleanField(default=False, help_text='Improve BET estimation if Field of View (FOV) is very small in Z (by temporarily padding end slices)')),
                ('remove_eyes', models.BooleanField(default=False, help_text='Remove eye and optic nerve')),
                ('surfaces', models.BooleanField(default=False, help_text='Run bet2 and then betsurf to get addiotional skull and scalp surfaces (includes registration)')),
                ('functional', models.BooleanField(default=False, help_text='Apply to 4D fMRI data')),
                ('reduce_bias', models.BooleanField(default=False, help_text='Bias field and neck cleanup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('brain', models.FilePathField(match='*.nii*', path='/export/home/zvibaratz/Projects/pylabber/media/nipype', recursive=True)),
                ('skull', models.FilePathField(match='*.nii*', path='/export/home/zvibaratz/Projects/pylabber/media/nipype', recursive=True)),
                ('binary_mask', models.FilePathField(match='*.nii*', path='/export/home/zvibaratz/Projects/pylabber/media/nipype', recursive=True)),
                ('outline', models.FilePathField(match='*.nii*', path='/export/home/zvibaratz/Projects/pylabber/media/nipype', recursive=True)),
                ('mesh', models.FilePathField(path='/export/home/zvibaratz/Projects/pylabber/media/nipype', recursive=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BetRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('in_file', models.FilePathField(match='*.nii*', max_length=255, path='/export/home/zvibaratz/Projects/pylabber/media/MRI', recursive=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='existing_runs', to='django_nipype.BetConfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='betresults',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='django_nipype.BetRun'),
        ),
    ]
