# Generated by Django 2.1.4 on 2019-02-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betresults',
            name='mask',
            field=models.FilePathField(blank=True, match='*.nii*', null=True, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='mesh',
            field=models.FilePathField(blank=True, match='*.vtk', null=True, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='out_file',
            field=models.FilePathField(blank=True, match='*.nii*', null=True, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='outline',
            field=models.FilePathField(blank=True, match='*.nii*', null=True, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='skull',
            field=models.FilePathField(blank=True, match='*.nii*', null=True, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='betrun',
            name='in_file',
            field=models.FilePathField(match='*.nii*', max_length=255, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='flirtresults',
            name='log',
            field=models.FilePathField(blank=True, match='*.log', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media'),
        ),
        migrations.AlterField(
            model_name='flirtresults',
            name='matrix',
            field=models.FilePathField(blank=True, match='*.mat', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media'),
        ),
        migrations.AlterField(
            model_name='flirtresults',
            name='out_file',
            field=models.FilePathField(blank=True, match='*.nii*', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media'),
        ),
        migrations.AlterField(
            model_name='flirtrun',
            name='in_file',
            field=models.FilePathField(match='*.nii*', max_length=255, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
        migrations.AlterField(
            model_name='flirtrun',
            name='reference',
            field=models.FilePathField(match='*.nii*', max_length=255, path='/home/flavus/Projects/pylabber/media', recursive=True),
        ),
    ]
