# Generated by Django 2.1.4 on 2019-01-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betconfiguration',
            options={'verbose_name_plural': 'Configurations'},
        ),
        migrations.AlterModelOptions(
            name='betresults',
            options={'verbose_name_plural': 'Results'},
        ),
        migrations.AlterModelOptions(
            name='betrun',
            options={'verbose_name_plural': 'Runs'},
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='functional',
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='padding',
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='reduce_bias',
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='remove_eyes',
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='robust',
        ),
        migrations.RemoveField(
            model_name='betconfiguration',
            name='surfaces',
        ),
        migrations.AddField(
            model_name='betconfiguration',
            name='mode',
            field=models.CharField(choices=[(None, 'Normal'), ('ROBU', 'Robust'), ('PADD', 'Padding'), ('REMO', 'Remove Eyes'), ('SURF', 'Surfaces'), ('FUNC', 'Functional'), ('REDU', 'Reduce Bias')], default=None, max_length=4),
            preserve_default=False,
        ),
    ]
