# Generated by Django 2.1.7 on 2019-03-26 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0002_auto_20190210_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='betconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
