# Generated by Django 2.1.4 on 2019-01-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0002_auto_20190122_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betconfiguration',
            name='mode',
            field=models.CharField(choices=[(None, 'Normal'), ('ROBU', 'Robust'), ('PADD', 'Padding'), ('REMO', 'Remove Eyes'), ('SURF', 'Surfaces'), ('FUNC', 'Functional'), ('REDU', 'Reduce Bias')], default=None, max_length=4),
        ),
    ]
