# Generated by Django 2.2 on 2019-04-06 16:00

from django.db import migrations, models
import django_nipype.models.interfaces.fsl.bet.choices.mode


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0002_auto_20190406_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betconfiguration',
            name='mode',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('ROBUST', 'Robust'), ('PADDNG', 'Padding'), ('REMOVE', 'Remove Eyes'), ('SURFAC', 'Surfaces'), ('FUNCTN', 'Funational'), ('REDUBI', 'Reduce Bias')], default=django_nipype.models.interfaces.fsl.bet.choices.mode.Mode('Normal'), max_length=7),
        ),
    ]
