# Generated by Django 2.1.4 on 2019-02-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0003_auto_20190201_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betresults',
            old_name='binary_mask',
            new_name='mask',
        ),
    ]
