# Generated by Django 2.1.4 on 2019-02-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0004_auto_20190201_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlirtResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('out_file', models.FilePathField(blank=True, match='*.nii*', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flirtconfiguration',
            name='log',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flirtrun',
            name='results',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results_for', to='django_nipype.FlirtResults'),
        ),
    ]
