# Generated by Django 2.1.5 on 2019-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0004_auto_20190123_1210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='betconfiguration',
            options={'verbose_name_plural': 'BET Configurations'},
        ),
        migrations.AlterField(
            model_name='betconfiguration',
            name='mode',
            field=models.CharField(blank=True, choices=[(None, 'Normal'), ('ROBU', 'Robust'), ('PADD', 'Padding'), ('REMO', 'Remove Eyes'), ('SURF', 'Surfaces'), ('FUNC', 'Functional'), ('REDU', 'Reduce Bias')], default=None, max_length=4),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='binary_mask',
            field=models.FilePathField(match='*.nii*', path='/home/zvi/Projects/pylabber/media/nipype', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='brain',
            field=models.FilePathField(match='*.nii*', path='/home/zvi/Projects/pylabber/media/nipype', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='mesh',
            field=models.FilePathField(path='/home/zvi/Projects/pylabber/media/nipype', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='outline',
            field=models.FilePathField(match='*.nii*', path='/home/zvi/Projects/pylabber/media/nipype', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='skull',
            field=models.FilePathField(match='*.nii*', path='/home/zvi/Projects/pylabber/media/nipype', recursive=True),
        ),
        migrations.AlterField(
            model_name='betrun',
            name='in_file',
            field=models.FilePathField(match='*.nii*', max_length=255, path='/home/zvi/Projects/pylabber/media/MRI', recursive=True),
        ),
    ]
