# Generated by Django 2.1.7 on 2019-04-03 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0004_auto_20190403_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betrun',
            name='results',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results_for', to='django_nipype.BetResults'),
        ),
    ]
