# Generated by Django 2.2 on 2019-04-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0004_auto_20190406_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betinput',
            name='path',
            field=models.FilePathField(max_length=500),
        ),
    ]
