# Generated by Django 2.1.5 on 2019-01-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0005_auto_20190127_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlirtConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('interpolation', models.CharField(choices=[('TL', 'Trilinear'), ('NN', 'Nearest Neighbor'), ('SP', 'Spline'), ('SI', 'Sinc')], default='TL', max_length=2)),
                ('cost_function', models.CharField(choices=[('MUT', 'Mutual Information'), ('COR', 'Correlation Ratio'), ('NCO', 'Normalized Correlation'), ('NMU', 'Normalized Mutual Information'), ('LSQ', 'Least Squares'), ('LBL', 'Label Difference'), ('BBR', 'Boundary-Based Registration')], default='COR', max_length=3)),
                ('bins', models.PositiveIntegerField(default=256)),
                ('degrees_of_freedom', models.PositiveIntegerField(default=12)),
                ('intensity_clamping', models.BooleanField(default=True)),
                ('resample_blur', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'FLIRT Configurations',
            },
        ),
    ]
