# Generated by Django 2.1.4 on 2019-02-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0005_auto_20190201_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='flirtresults',
            name='log',
            field=models.FilePathField(blank=True, match='*.log', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media'),
        ),
    ]
