# Generated by Django 2.1.7 on 2019-04-03 18:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0005_auto_20190403_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='betrun',
            name='log',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
