# Generated by Django 2.1.4 on 2019-02-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0006_flirtresults_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='flirtconfiguration',
            name='matrix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flirtresults',
            name='matrix',
            field=models.FilePathField(blank=True, match='*.mat', null=True, recursive=True, verbose_name='/home/flavus/Projects/pylabber/media'),
        ),
    ]
