# Generated by Django 2.1.5 on 2019-01-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0006_flirtconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betresults',
            name='binary_mask',
            field=models.FilePathField(match='*.nii*', path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='brain',
            field=models.FilePathField(match='*.nii*', path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='mesh',
            field=models.FilePathField(path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='outline',
            field=models.FilePathField(match='*.nii*', path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
        migrations.AlterField(
            model_name='betresults',
            name='skull',
            field=models.FilePathField(match='*.nii*', path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
        migrations.AlterField(
            model_name='betrun',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django_nipype.BetConfiguration'),
        ),
        migrations.AlterField(
            model_name='betrun',
            name='in_file',
            field=models.FilePathField(match='*.nii*', max_length=255, path='/media/zvi/Data/Data/pylabber', recursive=True),
        ),
    ]
