# Generated by Django 2.1.5 on 2019-01-27 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_nipype', '0007_auto_20190127_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlirtRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('in_file', models.FilePathField(match='*.nii*', max_length=255, path='/media/zvi/Data/Data/pylabber', recursive=True)),
                ('reference', models.FilePathField(match='*.nii*', max_length=255, path='/media/zvi/Data/Data/pylabber', recursive=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='django_nipype.FlirtConfiguration')),
            ],
            options={
                'verbose_name_plural': 'FLIRT Runs',
            },
        ),
    ]
